<a href="httpgetwrap|http://homevalues.azcentral.com"><img src="http://www.azcentral.com/email/newsletters/ads/images/homevalues.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
	<a href="httpgetwrap|http://homevalues.azcentral.com"><h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center;">Sell, buy or snoop! What's your neighborhood worth?</h2></a>

						<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >
						We're mapping the Valley's changing world of real estate.  Find out if your neighborhood is winning or losing.
						</p>