<a href="httpgetwrap|http://www.azcentral.com/photo/Community/PhoenixCentral/21867/568619"><img border="0" src="http://www.azcentral.com/email/newsletters/ads/images/community-phoenix.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
<a href="httpgetwrap|http://www.azcentral.com/photo/Community/PhoenixCentral/21867/568619"><h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center; text-decoration:none;">Fallen MCSO officers</h2></a>

<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >Seventeen officers with the Maricopa County Sheriff's Office  have died in the line of duty.</p>

 
 
