<a href="httpgetwrap|http://www.azcentral.com/community/scottsdale/articles/2012/01/09/20120109phoenix-scottsdale-priciest-home-sales-2012-prog.html"><img border="0" src="http://www.azcentral.com/email/newsletters/ads/images/community-scottsdale.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
<a href="httpgetwrap|http://www.azcentral.com/community/scottsdale/articles/2012/01/09/20120109phoenix-scottsdale-priciest-home-sales-2012-prog.html"><h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center; text-decoration:none;">Valley's priciest homes</h2></a>

<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >Each week, The Republic publishes information about the biggest real estate deals in the Valley. Here is a look at 2012.</p>

 
 
