<a href="httpgetwrap|http://www.azcentral.com/community/ahwatukee/20120423ahwatukee-woman-mobile-retail-shops-man-cave"><img border="0" src="http://www.azcentral.com/email/newsletters/ads/images/man-cave-promo.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
<a href="httpgetwrap|http://www.azcentral.com/community/ahwatukee/20120423ahwatukee-woman-mobile-retail-shops-man-cave"><h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center; text-decoration:none;">This Man Cave is ready to roll</h2></a>

<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >Ahwatukee woman runs four mobile retail shops, including one that offers haircuts.</p>

 
 
