<a href="httpgetwrap|http://www.dealchicken.com/phoenix-az"><img src="http://www.azcentral.com/email/newsletters/ads/images/deal-chicken.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
	<a href="httpgetwrap|http://www.dealchicken.com"><h2 style="font-size:14px; text-decoration:none; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center">Save up to 90% off on coupons and deals at DealChicken.com! </h2></a>

						<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >
						Coupons and deals up to 90% off! We hatch local deals daily! Sign up today! 
						</p>

