<a href="httpgetwrap|http://www.azcentral.com/news/politics/"><img src="http://www.azcentral.com/email/newsletters/ads/images/azcentral-politics.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
	<a href="httpgetwrap|http://www.azcentral.com/news/politics/"><h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center;">Check out our new politics section</h2></a>

						<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >
						Follow all of the developments throughout the political season at politics.azcentral.com, the new politics site powered by The Arizona Republic, azcentral.com and 12 News.</p>