<img src="http://www.azcentral.com/email/newsletters/ads/images/sports-newsletter.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  />
	<h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center;">Stay up to date with your favorite AZ teams.</h2>

						<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >
						Download the azcentral sports app from iTunes to get latest headlines, blogs, photos and stats from your favorite Arizona teams.
						</p>