<a href="httpgetwrap|http://www.azcentral.com/thingstodo/movies/search/?todowhat=&todowhere=Phoenix&todowhen=Anytime&x=33&y=7"><img border="0" src="http://www.azcentral.com/email/newsletters/ads/images/goodykoontz-on-movies.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
	<a href="httpgetwrap|http://www.azcentral.com/thingstodo/movies/search/?todowhat=&todowhere=Phoenix&todowhen=Anytime&x=33&y=7"><h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center; text-decoration:none;">Go to the movies
</h2></a>

						<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >
Search for the film times at the theater in your area. We'll see you at the movies.</p>

 
 
