<a href="httpgetwrap|http://www.azfactcheck.com"><img border="0" src="http://www.azcentral.com/email/newsletters/ads/images/azfactcheck.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
	<a href="httpgetwrap|http://www.azfactcheck.com"><h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center; text-decoration:none;">Are your public officials telling the truth?
</h2></a>

						<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >
AZ Fact Check helps keep Arizona officials honest by rating the truthfulness of their political statements. Visit <a href="httpgetwrap|http://www.azfactcheck.com">azfactcheck.com</a> today.</p>

 
 
