<a href="httpgetwrap|http://www.azcentral.com/news/traffic" border="0"><img src="http://www.azcentral.com/email/newsletters/ads/images/12news_traffic.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
	<a href="httpgetwrap|http://www.azcentral.com/news/traffic"><h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; text-decoration:none; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center;">Map your route and get there faster </h2></a>

						<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >
						12 News Beat the Traffic with its interactive map is your tool to get around wrecks, construction and traffic tie-ups when you are on the road.
						</p>