<a href="httpgetwrap|http://www.azcentral.com/community/gilbert/articles/2012/02/24/20120224gilbert-judge-nicole-laurin-rock-singer-walker-love-me-nots.html
"><img border="0" src="http://www.azcentral.com/email/newsletters/ads/images/community-gilbert.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
<a href="httpgetwrap|http://www.azcentral.com/community/gilbert/articles/2012/02/24/20120224gilbert-judge-nicole-laurin-rock-singer-walker-love-me-nots.html
"><h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center; text-decoration:none;">Gilbert judge likes to rock and rule</h2></a>

<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >Nicole Laurin-Walker is a municipal judge by day and a rock singer at night.</p>

 
 
