<a href="httpgetwrap|http://www.azcentral.com/community/glendale/articles/2012/03/01/20120301glendale-peoria-surprise-sun-city-libraries-prog.html"><img border="0" src="http://www.azcentral.com/email/newsletters/ads/images/community-glendale.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
<a href="httpgetwrap|http://www.azcentral.com/community/glendale/articles/2012/03/01/20120301glendale-peoria-surprise-sun-city-libraries-prog.html"><h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center; text-decoration:none;">Guide to Glendale libraries
</h2></a>

<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >Check out this comprehensive guide to public libraries in your area and take advantage of everything these facilities have to offer.</p>

 
 











 
 
