<a href="httpgetwrap|http://www.azcentral.com/community/pinal/articles/2012/04/30/20120430arizona-cps-foster-system-family.html"><img border="0" src="http://www.azcentral.com/email/newsletters/ads/images/foster-family-promo.jpg" border="0" width="190" height="54" border="0" style="margin:0; padding:0; width:190px; height:54px;"  /></a>
<a href="httpgetwrap|http://www.azcentral.com/community/pinal/articles/2012/04/30/20120430arizona-cps-foster-system-family.html"><h2 style="font-size:14px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#0E457B; margin:5px 8px 0 8px; padding:0; text-align:center; text-decoration:none;">QC family has taken in 160 kids over past 28 years</h2></a>

<p style="padding:0; margin:5px 8px 12px 8px; font-size:12px;" >The Reeds work with birth parents with the hope to see the children returned to their families.</p>

 
 
